export const Colors = {
  light: {
    background: "#fff",
    cardBackground: "#f9f9f9",
    text: "#333",
    textSecondary: "#666",
    textTertiary: "#888",
    primary: "#007AFF",
    border: "#eee",
    accent: "#66B2FF",
    success: "#28a745",
    warning: "#FFD700",
    exerciseCardBg: "#fff",
    exerciseCardBorder: "#007AFF",
  },
  dark: {
    background: "#000",
    cardBackground: "#1c1c1e",
    text: "#f0f0f0",
    textSecondary: "#d0d0d0",
    textTertiary: "#b0b0b0",
    primary: "#0A84FF",
    border: "#333",
    accent: "#64D2FF",
    success: "#30D158",
    warning: "#FFD60A",
    exerciseCardBg: "#2c2c2e",
    exerciseCardBorder: "#0A84FF",
  },
};
